version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped

  celery_worker:
    build: ../src
    container_name: celery_worker
    command: uv run celery -A src.app.core.celery.celery_app worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery_beat:
    build: ../src
    container_name: celery_beat
    command: uv run exec celery -A src.app.core.celery.celery_app beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
