volumes:
  postgres_data:

networks:
  yadro_net:

services:
  app:
    build:
      context: ../src
      dockerfile: Dockerfile
    container_name: yadro_app
    command: 
      - /bin/sh
      - -c
      - |
        poetry run alembic upgrade head;
        poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - ../src/.env
    depends_on:
      - db
    restart: always
    networks:
      - yadro_net

  db:
    image: postgres:15-alpine
    container_name: yadro_db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../src/.env
    networks:
      - yadro_net
