"""aboba

Revision ID: c055b548ea49
Revises: b370eb4fdd68
Create Date: 2025-06-02 15:33:58.360362

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "c055b548ea49"
down_revision: Union[str, None] = "b370eb4fdd68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "urlpair",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("short_url", sa.String(length=255), nullable=False),
        sa.Column("original_url", sa.String(), nullable=False),
        sa.Column("is_activated", sa.Boolean(), nullable=False),
        sa.Column("is_old", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("short_url"),
    )
    op.create_table(
        "urlpairstat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url_id", sa.Integer(), nullable=False),
        sa.Column("last_hour_clicks", sa.Integer(), nullable=False),
        sa.Column("last_day_clicks", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["url_id"], ["urlpair.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url_id"),
    )
    op.drop_table("url")
    op.drop_table("clickstat")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clickstat",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('clickstat_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "last_hour_clicks", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("last_day_clicks", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="clickstat_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "url",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("short_url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("original_url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("is_activated", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("is_old", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("clickstat_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["clickstat_id"], ["clickstat.id"], name=op.f("url_clickstat_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("url_pkey")),
        sa.UniqueConstraint(
            "clickstat_id",
            name=op.f("url_clickstat_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "short_url",
            name=op.f("url_short_url_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table("urlpairstat")
    op.drop_table("urlpair")
    # ### end Alembic commands ###
