"""add_url

Revision ID: ddbca2fe4aaa
Revises: 5242a0a55c8a
Create Date: 2025-05-31 23:45:52.261475

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "ddbca2fe4aaa"
down_revision: Union[str, None] = "5242a0a55c8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "url",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("short_url", sa.String(), nullable=False),
        sa.Column("original_url", sa.String(), nullable=False),
        sa.Column("is_activated", sa.Boolean(), nullable=False),
        sa.Column("is_old", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_url_short_url"), "url", ["short_url"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_url_short_url"), table_name="url")
    op.drop_table("url")
    # ### end Alembic commands ###
