"""add_stats

Revision ID: bf7b9ff34df6
Revises: ddbca2fe4aaa
Create Date: 2025-05-31 23:53:58.450567

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "bf7b9ff34df6"
down_revision: Union[str, None] = "ddbca2fe4aaa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clickstat",
        sa.Column("link_id", sa.Integer(), nullable=False),
        sa.Column("last_hour_clicks", sa.Integer(), nullable=False),
        sa.Column("last_day_clicks", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["link_id"], ["url.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("link_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("clickstat")
    # ### end Alembic commands ###
