"""add_expire

Revision ID: 3a07827bf1a1
Revises: c055b548ea49
Create Date: 2025-06-03 23:38:56.221130

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "3a07827bf1a1"
down_revision: Union[str, None] = "c055b548ea49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "urlpair", sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("urlpair", "expires_at")
    # ### end Alembic commands ###
