"""check

Revision ID: b370eb4fdd68
Revises: 
Create Date: 2025-06-02 12:14:50.068726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b370eb4fdd68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clickstat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_hour_clicks', sa.Integer(), nullable=False),
    sa.Column('last_day_clicks', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_url', sa.String(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('is_activated', sa.Boolean(), nullable=False),
    sa.Column('is_old', sa.Boolean(), nullable=False),
    sa.Column('clickstat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clickstat_id'], ['clickstat.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clickstat_id'),
    sa.UniqueConstraint('short_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_table('user')
    op.drop_table('clickstat')
    # ### end Alembic commands ###
