"""fix_relation

Revision ID: 6f33909135bb
Revises: 2d015573799c
Create Date: 2025-06-01 12:22:18.982736

"""

from typing import Sequence, Union



revision: str = "6f33909135bb"
down_revision: Union[str, None] = "2d015573799c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
