"""fix_relations

Revision ID: 2d015573799c
Revises: bf7b9ff34df6
Create Date: 2025-06-01 12:21:24.446782

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "2d015573799c"
down_revision: Union[str, None] = "bf7b9ff34df6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
