"""ref

Revision ID: d2d68c462647
Revises: 1bf5ea0abb2c
Create Date: 2025-06-02 00:58:32.896023

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "d2d68c462647"
down_revision: Union[str, None] = "1bf5ea0abb2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("clickstat_link_id_key"), "clickstat", type_="unique")
    op.drop_constraint(op.f("clickstat_link_id_fkey"), "clickstat", type_="foreignkey")
    op.drop_column("clickstat", "link_id")
    op.add_column("url", sa.Column("clickstats_id", sa.Integer(), nullable=False))
    op.create_unique_constraint(None, "url", ["clickstats_id"])
    op.create_foreign_key(None, "url", "clickstat", ["clickstats_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "url", type_="foreignkey")
    op.drop_constraint(None, "url", type_="unique")
    op.drop_column("url", "clickstats_id")
    op.add_column(
        "clickstat",
        sa.Column("link_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("clickstat_link_id_fkey"),
        "clickstat",
        "url",
        ["link_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        op.f("clickstat_link_id_key"),
        "clickstat",
        ["link_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
