"""refactoring

Revision ID: 1bf5ea0abb2c
Revises: 6f33909135bb
Create Date: 2025-06-02 00:35:37.668289

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "1bf5ea0abb2c"
down_revision: Union[str, None] = "6f33909135bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_url_short_url"), table_name="url")
    op.create_unique_constraint(None, "url", ["short_url"])
    op.add_column(
        "user",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.create_index(op.f("ix_user_created_at"), "user", ["created_at"], unique=False)
    op.drop_column("user", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False)
    )
    op.drop_index(op.f("ix_user_created_at"), table_name="user")
    op.drop_column("user", "created_at")
    op.drop_constraint(None, "url", type_="unique")
    op.create_index(op.f("ix_url_short_url"), "url", ["short_url"], unique=True)
    # ### end Alembic commands ###
