name: Style checker

on:
  workflow_call:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install uv
          cd src
          uv sync --all-groups

      - name: Ruff check
        id: ruff_check
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BASE_BRANCH=${{ github.event.pull_request.base.ref }}
          else
            BASE_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          fi

          git fetch origin $BASE_BRANCH --depth=1

          CHANGED_FILES=$(git diff --name-only origin/$BASE_BRANCH...HEAD -- '*.py')

          if [[ -n "$CHANGED_FILES" ]]; then
            poetry run ruff check $CHANGED_FILES || echo "Ruff found issues, formatting will be applied."
          else
            echo "No Python files changed."
          fi

      - name: Auto-format with Ruff (if issues found)
        if: steps.ruff_check.outcome == 'failure'
        run: |

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BASE_BRANCH=${{ github.event.pull_request.base.ref }}
          else
            BASE_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          fi

          git fetch origin $BASE_BRANCH --depth=1

          CHANGED_FILES=$(git diff --name-only origin/$BASE_BRANCH...HEAD -- '*.py')

          if [[ -n "$CHANGED_FILES" ]]; then
            poetry run ruff --fix $CHANGED_FILES
          else
            echo "No Python files to format."
          fi
